language: node_js
dist: trusty
sudo: false
node_js:
  - '8'
services:
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - psql -c "create database testing;" -U postgres
env:
  global:
    - DATABASE_URL="postgres://postgres@localhost:5432/testing"
