language: node_js
dist: trusty
sudo: false
node_js:
  - '8'
  - '9'
services:
  - postgresql
addons:
  postgresql: "10.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - psql -c "create database testing;" -U postgres
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.2
env:
  global:
    - DATABASE_URL="postgres://postgres@localhost:5432/testing"
