defaults:
  app:
    keyPrefix: 'ec2-manager:'
    instancePubKey: 'lalalalla'
    spotPollFreq: 200
    regions:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - eu-central-1
    queueName: 'ec2-events'
    ruleName: 'ec2-instance-state-transitions'
    publishMetadata: false
  ec2:
    apiVersion: 2014-01-01
  sqs:
    apiVersion: 2012-11-05
  cwe:
    apiVersion: 2015-10-07
  aws:
    accessKeyId: !env AWS_ACCESS_KEY_ID
    secretAccessKey: !env AWS_SECRET_ACCESS_KEY
    maxRetries: 10
  postgres:
    databaseUrl: !env DATABASE_URL
  server:
    port: 5555
    publicUrl: localhost:5555
    env: development
    forceSSL: false
    trustProxy: false
  monitor:
    project: ec2-manager
    mock: true
  taskcluster:
    authBaseUrl: https://auth.taskcluster.net/v1
    queueBaseUrl: https://queue.taskcluster.net/v1
    credentials:
      clientId: !env TASKCLUSTER_CLIENT_ID
      accessToken: !env TASKCLUSTER_ACCESS_TOKEN
development:
production:
  server:
    port: !env:number PORT
    env: production
    forceSSL: true
    trustProxy: true
  app:
    publishMetadata: true
test:
