defaults:
  app:
    keyPrefix: 'ec2-manager:'
    instancePubKey: 'lalalalla'
    spotPollDelay: 25
    houseKeepingPollDelay: 86400 # One day
    maxInstanceLifeHours: 96
    regions:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - eu-central-1
    queueName: 'ec2-events'
    ruleName: 'ec2-instance-state-transitions'
    publishMetadata: false
  ec2:
    apiVersion: 2014-01-01
  sqs:
    apiVersion: 2012-11-05
  cwe:
    apiVersion: 2015-10-07
  aws:
    accessKeyId: !env AWS_ACCESS_KEY_ID
    secretAccessKey: !env AWS_SECRET_ACCESS_KEY
    maxRetries: 10
  postgres:
    databaseUrl: !env DATABASE_URL
  server:
    port: 5555
    publicUrl: localhost:5555
    baseUrl: 'http://localhost:5555/v1'
    env: development
    forceSSL: false
    trustProxy: false
  monitor:
    project: ec2-manager
    mock: true
  taskcluster:
    authBaseUrl: https://auth.taskcluster.net/v1
    queueBaseUrl: https://queue.taskcluster.net/v1
    credentials:
      clientId: !env TASKCLUSTER_CLIENT_ID
      accessToken: !env TASKCLUSTER_ACCESS_TOKEN
development:
  app:
    keyPrefix: 'aws-provisioner-dev:'
    instancePubKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDbPJ9W0lOXMQX8+ooo054m96IRcyhEJZ+ocdBqklFSlyC+6UZPwDBoY3lmT1PPOE/niVYKjSGqGtnw9Y0iSEE1MuNvrLDzmFd3+mmHOhHVs6buDOdIFS+MXVyjcdhRoZBqCNg1tz9vvq1NXzYZ4DIWo8xQG/Xq5EKcsgRiitl6VfssCw6jZla8YEQ7ARk8EqJ1BbaMfW8PceiqkmpL/SPNnFyKkbnfVkiqjYarLJJZaW21Wq7eEcZZdUOaHuSpFdNlfGORuDD35VjQDNB+QximDrAEDUN2LOKmS718Yf6+w2k72PZkHwMUHxA4GvlkQO61v+Jm/A2fYTp3QPtQuKuh'
production:
  server:
    port: !env:number PORT
    env: production
    forceSSL: true
    trustProxy: true
    baseUrl: 'https://ec2-manager.herokuapp.com/v1'
  app:
    keyPrefix: 'aws-provisioner-v1-managed:'
    publishMetadata: true
  postgres:
    maxClients: 110
  monitor:
    project: ec2-manager
    mock: false
test:
  app:
    keyPrefix: 'ec2-manager-test:'
    instancePubKey: 'ssh-rsa pubkeydata'
    spotPollDelay: 200
